version: "3.8"  

services:
  mlflow_server:
    build: mlflow_server
    volumes:
      - ./mlflow_server/mlflow.db:/app/mlflow.db
    ports:
      - "5000:5000"
    tty: true

  mlflow_client:
    build: mlflow_client
    volumes: 
      - ./mlflow_client/models:/app/models
      - ./mlflow_client/data:/app/data
      - ./mlflow_client/graphs:/app/graphs
      - ./mlflow_client/predictions:/app/predictions

      - ./mlflow_client/config_rs.json:/app/config_rs.json
      - ./mlflow_client/config_one.json:/app/config_one.json
      - ./mlflow_client/config_predict.json:/app/config_predict.json

      - ./mlflow_server/mlflow.db:/app/mlflow.db
    tty: true



  